name: fatih
description: Benim Şahsi Uygulamam.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  splash_screen_view: ^3.0.0
  animated_bottom_navigation_bar: ^0.3.2
  google_fonts: ^2.2.0
  # Prerelease: 4.0.0-nullsafety hazır değil ama animasyonu kolaylaştırdağından dolayı on surum kullanıyorum
  flutter_sequence_animation: "^4.0.0-nullsafety"
  percent_indicator: ^4.0.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.3
  vertical_card_pager: ^1.5.0
  animated_background: ^2.0.0
  path_provider: ^2.0.10

  webview_flutter: ^3.0.4

  http: ^0.13.4
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  # google_sign_in: ^5.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/setup/
    - asset/rep/
    - asset/filmler/

