// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiJZEtyCbwb7Fdw9LpDUwvjIkCXSKYXFk',
    appId: '1:118357181506:web:85cb9f73082a61d99a99db',
    messagingSenderId: '118357181506',
    projectId: 'fatih-cc23c',
    authDomain: 'fatih-cc23c.firebaseapp.com',
    storageBucket: 'fatih-cc23c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT1eJTWC6hhKPNt2UFohCXh8TVtq3lvtg',
    appId: '1:118357181506:android:4d2258dfdc9624089a99db',
    messagingSenderId: '118357181506',
    projectId: 'fatih-cc23c',
    storageBucket: 'fatih-cc23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImB7PMVvCYZeyUoVIoFfQPvzq1mXbOz0',
    appId: '1:118357181506:ios:a4de80e42c449e6b9a99db',
    messagingSenderId: '118357181506',
    projectId: 'fatih-cc23c',
    storageBucket: 'fatih-cc23c.appspot.com',
    iosClientId: '118357181506-nv7jumuf1iv401ss22h6bppepdq7gcbg.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.fatih.fatih',
  );
}
